language: node_js

node_js:
- 8.9.4

sudo: required

jobs:
  include:
    - stage: install_test
      script:
        - cd client
        - yarn
        - yarn lint
        - yarn build
        - cd ..
        - cd server
        - yarn
        - cd ..
    - stage: deploy
      addons:
        ssh_known_hosts: 115.159.27.203
      script:
        - openssl aes-256-cbc -K $encrypted_f4d349a30759_key -iv $encrypted_f4d349a30759_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
        - chmod 600 ~/.ssh/id_rsa
        - echo -e "Host 115.159.27.203\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - pwd
      after_success:
        - ssh root@115.159.27.203 "cd /var/www/node/mail-system && git fetch && git pull && cd server && yarn && pm2 start app.js && cd .. ; exit 0"

notifications:
  email: false
